name: QC for lambda-ber-schema

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_COLOR: "1"

permissions: {}

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
      fail-fast: false

    steps:

      # https://github.com/actions/checkout
      - name: Check out repository
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      # https://github.com/astral-sh/setup-uv
      - name: Install uv
        uses: astral-sh/setup-uv@v6.4.3
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      # https://github.com/actions/setup-python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Just
        uses: extractions/setup-just@v3

      - name: Install project
        run: uv sync --dev

      - name: Run validations on examples
        run: just test-examples